
services:
  load_balancer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network

  server1:
    build:
      context: .
      dockerfile: Docker.server
    ports:
      - "5001:5000"
    networks:
      - app-network
    environment:
      - SERVER_NAME=server1

  server2:
    build:
      context: .
      dockerfile: Docker.server
    ports:
      - "5002:5000"
    networks:
      - app-network
    environment:
      - SERVER_NAME=server2

  server3:
    build:
      context: .
      dockerfile: Docker.server
    ports:
      - "5003:5000"
    networks:
      - app-network
    environment:
      - SERVER_NAME=server3

networks:
  app-network:
    driver: bridge

